sudo: required
arch:
  - amd64
  - ppc64le

language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libtirpc-dev libwrap0-dev libselinux-dev ; fi

script:
  - sh autogen.sh
  - ./configure --without-libwrap --without-labeled-networking --without-loadavg
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make distcheck ; fi
